# Generated by Django 3.2.11 on 2023-04-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftclock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
