# Generated by Django 3.2.11 on 2023-04-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiftclock', '0003_auto_20230410_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerapproval',
            name='approved',
        ),
        migrations.AddField(
            model_name='managerapproval',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shiftclock.employee'),
        ),
        migrations.AddField(
            model_name='managerapproval',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
