# Generated by Django 3.2.11 on 2023-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftclock', '0004_auto_20230410_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapproval',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
