# Generated by Django 3.2.11 on 2023-04-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftclock', '0005_alter_managerapproval_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('employee', 'date')},
        ),
    ]
